config/routes.rb
Rails.application.routes.draw do

  namespace :admins do
    get 'top' => 'homes#top', as:'top'  
  end
  devise_for :admins, controllers: {
  sessions:      'admins/sessions'
}


  get 'jobs/index'
  get 'jobs/edit'
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:index,:show,:create,:edit, :update, :destroy] do
    resources :nicetry, only: [:create,:destroy]
  end

  resources :jobs, only: [:index,:create, :edit, :update, :destroy]

  resources :projects do
    resource :favorites
    resources :comments, only: [:create, :destroy]
  end

  root 'homes#about'
  get '/homes/inquery' => 'homes#inquery'
  post '/homes/guest_sign_in', to: 'homes#new_guest'


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,:recoverable, :rememberable, :validatable

  has_many :projects, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  attachment :image
  validates :family_name, presence: true, length: { maximum: 15 }
  validates :first_name, presence: true, length: { maximum: 15 }
  validates :email, presence: true, length: {maximum: 50 }
  

  def self.search(search)
    if search
      if Rails.env.production?
        #本番環境Mysql2の場合
        where(['concat(family_name, first_name) like ?', "%#{search}%"])
      else
        #テスト環境sqlite3の場合
        where(['(family_name || first_name) like ?', "%#{search}%"])
      end
    else
      all
    end
  end

  def full_name
    return self.family_name + self.first_name
  end

  def user_image
    unless self.image_id.nil?
      @image_url = "https://image-files-resize-niduka.s3-ap-northeast-1.amazonaws.com/store/" + self.image_id + "-thumbnail."
    else 
      @image_url = "https://image-files-original-niduka.s3-ap-northeast-1.amazonaws.com/no_image.jpg"  
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :destroy]
  def index
    @users = User.all.page(params[:page]).search(params[:search])

    @user = User.includes(:users)

  end

  def show
    @user = User.find(params[:id])
    @projects_count = Project.where(user_id: @user).count
    @projects = @user.projects.order("created_at DESC").page(params[:page]).per(10)
    @image_url = @user.user_image
  end
  def edit
    @user = User.find(params[:id])
    @image_url = @user.user_image
    if @user != current_user
      redirect_to user_path(current_user)
      flash[:danger] = '編集画面は自分のアカウントでログインしてださい'

    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      sleep(3) # S3への画像反映のタイムラグ
      flash[:success] = 'プロフィールを更新しました(更新の反映に数分かかる場合があります)'
      redirect_to user_path(@user)
    else
      @user = current_user
      flash[:danger] = '投稿に失敗しました'
      render :edit
    end
  end
  private
  def user_params
    params.require(:user).permit(:family_name,:first_name,:image, :image_id,:admin_status, :email)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h2 class="page-header text-center">登録情報編集</h2><br>
  <div class="row center">
    <div class="col-md-8 col-md-offset-2">
      <%= form_with(model:[@user], local: true) do |f| %>
        <table>
          <tr>
            <td>
              <div class= "form-group">
                  <%= f.label :"(姓)" %>
                  <%= f.text_field :family_name, class: 'form-control', placeholder: "例:田中" %>
              </div>
              </td>
              <td>　</td>
            <td>
              <div class= "form-group">
                  <%= f.label :"(名)" %>
                <%= f.text_field :first_name, class: 'form-control', placeholder: "例:太郎" %>
              </div>
            </td>
          </tr>
        </table>
      <div class="form-group has-icon">
        <div class="user-edit-image">
          <%= image_tag @image_url,size: "60x60",class: "img-circle pull-left profile-thumb" %>
        </div>
        <%= f.attachment_field :image, placeholder: "プロフィール画像", class: "user-edit-form" %>
      </div>
      
      <div class= 'text-center'>
        <%= f.submit '編集する', class:"btn btn-primary" %>
      </div>
      <% end %>
    </div>
  </div>

app/views/users/index.html.erb
<div class= "row">
  <div class= "col-md-8 col-md-offset-2">
    <h2 class="page-header text-center border-bottom">会員一覧</h2>
    <table class= "table">
      <th></th>
      <th>会員id</th>
      <th>会員名</th>
      <th>提案数</th>
      <th><p></p></th>
      <% provide(:title, 'All users') %>
      <%= form_tag users_path, :method => 'get' do %>
        <%= text_field_tag :search,params[:search] %>
        <%= submit_tag '検索', :name => nil %>
      <% end %>

      <ul class="media-list">
          </ul>
      <% @users.each do |user| %>
        <tr>
          <td>
            <div class="icon-image">
              <%= image_tag user.user_image, size:'40x40', class: "img-circle pull-left profile-thumb" %>
            </div>
          </td>
            <td> <%= user.id %> </td>
            <td> <%= link_to user.full_name,user_path(user.id) %></td>
            <td><%= user.projects.count %>回</td>
            <td>
              <% if user == current_user %> 
                <%= link_to "編集", edit_user_path(user),class:"btn btn-primary" %>
              <% end %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/users/show.html.erb
<div class="row show-user">
  <div class="col-md-10  col-md-offset-1 text-center">
    <h2><%= @user.full_name %>のページ</h2>
    <%= image_tag @image_url,size: "60x60", class: "img-circle profile-thumb center-block" %>
      <% if @user == current_user %>
        <%= link_to "プロフィールを編集",edit_user_path, {class: "show-user__btn btn btn-success"} %>
      <% end %>
    <div class= "show-user__contents">
      <h3 class="text-center">これまでの提案数：<%= @projects_count %>件</h3>
      <h2 class= "text-center">最近提案したプロジェクト</h2>
      <div class="table-responsive">
        <table class="table table-striped table-sm">
          
          <% if @projects_count == 0 %>
            <h2>まだ改善を投稿してません</h2>
            <%= link_to "ここから改善を始めよう",new_project_path, {class: "btn btn-primary"} %>
          <% else %>
          <tr>
            <th>No.</th>
            <th>タイトル</th>
            <th>改善時間</th>
            <th>いいね数</th>
            <th>コメント数</th>
            <th>ステータス</th>
            <th></th>
          </tr>
            <% @projects.each do |project| %>
              <tr>
                <td><%= project.id %></td>
                <td><%= link_to project.name, project_path(project) %></td>
                <td>
                  <% if project.reducation_time >= 60 %>
                    <%= project.reducation_time / 60 %>時間 
                    <%= project.reducation_time % 60 %>分</td>
                  <% else %>
                    <%= project.reducation_time %>分
                  <% end %>
                </td>
                <td><%= project.favorites.count %>件</td>
                <td><%= project.comments.count %>件</td>
                <td><%= project.status %></td>
                <% if project.user == current_user %>
                  <td><%= link_to "編集",edit_project_path(project), {class: "btn btn-success"} %></td>
                <% end %>
              </tr>
            <% end %>
          <% end %>
        </table>
      </div>
      <%= paginate @projects %>
    </div>
  </div>
</div>