config/routes.rb
Rails.application.routes.draw do

  namespace :admins do
    get 'top' => 'homes#top', as:'top'  
  end
  devise_for :admins, controllers: {
  sessions:      'admins/sessions'
}


  get 'jobs/index'
  get 'jobs/edit'
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:index,:show,:create,:edit, :update, :destroy] do
    resources :nicetry, only: [:create,:destroy]
  end

  resources :jobs, only: [:index,:create, :edit, :update, :destroy]

  resources :projects do
    resource :favorites
    resources :comments, only: [:create, :destroy]
  end

  root 'homes#about'
  get '/homes/inquery' => 'homes#inquery'
  post '/homes/guest_sign_in', to: 'homes#new_guest'


end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  
  belongs_to :job
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  validates :name, presence: true, length: {maximum: 50 };
  validates :content, presence: true, length: {maximum: 250 };
  validates :reducation_time, presence: true, numericality: true,length: {maximum: 10 };  
  
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

def reducation
  amount = self.reducation_time * ( self.job.amount / 60)
  if self.reducation_time >= 60 
        hour = self.reducation_time / 60
        min = self.reducation_time  % 60
        return "#{hour}時間#{min}分 #{amount}円"
    else
        min = self.reducation_time
        return "#{min}分 #{amount}円"
    end
end

def reducation_month
  amount = self.reducation_time * ( self.job.amount / 60) * self.number_of_month
  if (self.number_of_month * self.reducation_time) >= 60 
      hour = self.number_of_month * self.reducation_time / 60
      min = self.number_of_month * self.reducation_time  % 60
      return "#{hour}時間#{min}分 #{amount}円"
    else
      min = self.number_of_month * self.reducation_time
      return ":#{min}分 #{amount}円"
  end
end

def reducation_year
  amount = self.reducation_time * ( self.job.amount / 60) * self.number_of_month * 12
  if (self.number_of_month * self.reducation_time * 12)  >= 60 
        hour = self.number_of_month * self.reducation_time * 12 / 60
        min = self.number_of_month * self.reducation_time * 12  % 60
        return "#{hour}時間#{min}分 #{amount}円"
      else
        min = self.number_of_month * self.reducation_time * 12
        return "#{min}分 #{amount}円"
    end
end

def full_name
  return self.user.family_name + self.user.first_name 
end


  paginates_per 5
  enum status: {"アイデア募集中":0, "アクション中":1, "未達成":2, "達成":3}
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  require 'active_support/core_ext/numeric/conversions'
  before_action :authenticate_user!, only: [:new, :create, :edit, :update]
  
  def index
    @projects = Project.page(params[:page]).reverse_order
    #chart.js
    @user = Project.group(:user_id).pluck(:user_id) #取得idを元にUserテーブルのカラム
    @user_name = User.where(id: @user).pluck(:family_name ,:first_name)
    @data = Project.group(:user_id).sum(:reducation_time).values #時間を抽出
  end
  
  def new
    @project = Project.new
    @status = params[:status_selection]
  end

  def create
    @project = Project.new(project_params)
    @project.user_id = current_user.id
    job = Job.find(project_params[:job_id])
    job_amount = job.amount
    if @project.save
      redirect_to projects_path, notice: "提案を投稿しました！"
    else
      flash.now[:danger] = "投稿に失敗しました"
      render :new
    end
  end

  def edit
    @project = Project.find(params[:id])
    if @project.user_id != current_user.id
      redirect_to projects_path 
    end
  end

  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      redirect_to projects_path, notice: "ユーザー情報を更新しました！"
    else
      flash.now[:danger] = "投稿に失敗しました"
      render:edit
    end
  end

  def show
    @project = Project.find(params[:id])
    @image_url = @project.user.user_image
    @comment = Comment.new
    @comments = @project.comments.order("created_at DESC").page(params[:page]).per(5)
  end

  private
  def project_params
    params.require(:project).permit(:user_id,:name, :content,:job_id ,:start_date, :finish_date, :status, :reducation_time, :total_amount, :reducation_amount,:number_of_month)
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
  
end

app/views/projects/_form.html.erb
<div class="col-md-offset-3 col-md-6">
  <div class="contants_form">
    <h2 class="page-header text-center border-bottom">提案ページ</h2>
    <%= form_with(model: [project], local: true) do |f| %>
      <div class= "form-group">
        <%= f.label :"業務改善のタイトル" %> <span class="label label-danger">必須</span>
        <%= f.text_field :name, class: 'form-control', placeholder:"例:〇〇の改善" %>
      </div>
      <div class="form-group">
        <%= f.label :"業務改善の内容" %><span class="label label-danger">必須</span>
        <%= f.text_area :content, rows:10 ,class: 'form-control', placeholder:"ここに業務改善の内容を追加してください" %>
      </div>
      <div class="form-group  select">
        <%= f.label :"職種" %>
        <%= f.collection_select :job_id, Job.all, :id, :name, class:"form-control" %>
      </div>
      <div class="form-group ">
        <%= f.label :"作業の月回数 約" %>
        <%= f.select :number_of_month, [*1..31], class: 'form-controlselect' %>回
      </div>
      <div class="form-group select">
        <%= f.label :"１回当たりの削減時間" %><span class="label label-danger">必須</span>
        <label><%= f.text_field :reducation_time, class: 'reducation_min' %> 分</label>
      </div>
      <div class="form-group">
        <%= f.label :"開始予定日" %>
        <%= raw sprintf(
          f.date_select(:"start_date",   
          use_month_numbers: true,
          start_year:        2020,
          end_year:          (Time.now.year + 20),
          default:           Date.new(2020, 1, 1),
          date_separator:    '%s'), # 年月日区切りをそれぞれ指定
              '年 ', '月 ' , class: 'form-control') + '日'%>
      </div>
      <div class="form-group">
        <%= f.label :"終了予定日" %>
        <%= raw sprintf(
        f.date_select(:"finish_date",   
        use_month_numbers: true,
        start_year:        2020,
        end_year:          (Time.now.year + 20),
        default:           Date.new(2020, 1, 1),
        date_separator:    '%s'), # 年月日区切りをそれぞれ指定
            '年 ', '月 ' , class: 'form-control') + '日' %>
      </div>

      <div class="form-group"> 
        <%= f.label :"ステータス" %>
        <%= f.select :status, Project.statuses.keys.to_a %>
      </div>
      <div class="btn-position">
        <%= f.submit '投稿する', class:"btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/projects/edit.html.erb
<div class="row center">
  <h2 class="page-header text-center">プロジェクト情報編集</h2><br>
  <%= render partial: 'form', locals: { project: @project} %>
</div>

app/views/projects/index.html.erb
<h2 class="page-header text-center border-bottom">提案一覧</h2>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <!-- Graphs -->
    <canvas id="myChart" width="900" height="400"></canvas>
    <script>
      var ctx = document.getElementById("myChart").getContext('2d');
      var myChart = new Chart(ctx, {
        type: 'bar',
        data: {
          labels:  <%= @user_name.to_json.html_safe %>,
          datasets: [{
              label: "削減総時間",
              data: <%= @data %>,
              backgroundColor: 'rgba(255, 99, 132, 1.0)',
              borderColor: 'rgba(255, 50, 132, 1.0)',
              fill: false
          }]
        },
        options: {
            title:  {
              display: true,
              text: "ユーザー別改善時間/年"
            }
        }
      });
    </script>
    <table class="table table-striped table-inverse">
        <th>No.</th>
        <th>タイトル<br>職種<br>職種の時間単価</th>
        <th>改善時間・金額</th>
        <th>その他費用</th>
        <th>ステータス<br>開始予定<br>終了予定</th>
        <th>提案者</th>
        <th>いいね・コメント</th>
        <th></th>

      
      <% @projects.each do |project| %>
        <tr>
          <td><%= project.id %></td>
          <td><%= link_to project.name ,project_path(project) %><br>
          <%= project.job.name %><br><%= project.job.amount %>円</td>
          
          <td>
            1回:<%= project.reducation %><br>
            月<%= project.reducation_month %><br>
            年:<%= project.reducation_year %>
          </td>
          <td>
            1回:<%= project.reducation_amount.to_s(:delimited) %>円<br>
            月:<%= (project.number_of_month * project.reducation_amount).to_s(:delimited) %>円 <br>
            年:<%= ((project.number_of_month * 12) * project.reducation_amount).to_s(:delimited) %>円
          </td>
          <td>
            <%= project.status %><br>
            <%= project.start_date %><br>
            <%= project.finish_date %>
          </td>
          <td><%= link_to project.full_name, user_path(project.user) %></td>
          <td>
            <small>
              <% if user_signed_in? %>
                <% if project.favorited_by?(current_user) %>
                  <%= link_to project_favorites_path(project), method: :delete do %>
                    <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
                    <%= project.favorites.count %> いいね
                  <% end %>
                <% else %>
                  <%= link_to project_favorites_path(project), method: :post do %>
                    <i class="fa fa-heart-o" aria-hidden="true"></i>
                    <%= project.favorites.count %> いいね
                  <% end %>
                <% end %>
              <% else %>
                <i class="fa fa-heart-o" aria-hidden="true"></i>
                <%= project.favorites.count %> いいね
              <% end %>
            </small>
            <small><i class="fas fa-comment"> <%= project.comments.count %></i>件</small>
          </td>
          <td>
            <% if project.user == current_user %>
              <%= link_to "編集",edit_project_path(project), {class: "btn btn-success"} %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
    <%= paginate @projects %>
  </div>
</div>

app/views/projects/new.html.erb
<div class="row project-new">
  <div class="text-center">
    <% if @project.errors.any? %>
      <h2> <%= pluralize(@project.errors.count, "error") %> prohibited this obj from being saved: </h2>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %> 
    <% end %>
  </div>
  <%= render partial: 'form', locals: { project: @project} %>
</div>

app/views/projects/show.html.erb
  <div class="row project_page">
    <div class="col-md-offset-1 col-md-10">
      <h2>プロジェクト詳細</h2>
      <div class="project">
        <div class="project-date"> 投稿日:<%= @project.created_at.strftime('%Y/%m/%d') %></div>
        <div class="project_no"> No.<%= @project.id %></div>
        <div class="project_title"> 改善提案名</div>
        <div class="project-name"><%= @project.name %></div>
        <div class="project-content_title"> 提案内容</div>
        <div class="project-content"><%= @project.content %></div>
        <div class="project_block">
          <div class="project_user">
            <div class="user_data1">
              <div class="project_user_title">提案者</div>
              <div class= "project_user_image"><%= image_tag @image_url, size:'40x40', class: "img-circle profile-thumb" %></div>
              <div class="user_name"><%= @project.full_name %></div>
            </div> 
            <div class="user_data2">
              <div class="favo">いいね <i class="fa fa-heart" aria-hidden="true" style="color: red;">
              <%= @project.favorites.count %></i>件</div>
              <div class="comment">コメント<i class="fas fa-comment"> <%= @project.comments.count %></i>件</div>
            </div>
          </div>
          <div class="project_info">
            <div class="status">ステータス:<%= @project.status %></div>
            <div class="start">開始予定日:<%= @project.start_date %></div>
            <div class="finish">終了予定日:<%= @project.finish_date %></div>
          </div>
          <div class="project_reducation">
            <div class="project_reducation_1">作業の月回数：<%= @project.number_of_month %>回</div>
            <div class="project_reducation_2">１回の削減時間：<%= @project.reducation %></div>
            <div class="project_reducation_3">月の削減時間:<%= @project.reducation_month %></div>
            <div class="project_reducation_4">年間の削減時間:<%= @project.reducation_year %></div> 
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <h2>コメント一覧</h2>
      </div>
      <div class="col-md-offset-2 col-md-4">
        <div id='comments_area'>
          <%= render partial: 'comments/index', locals: { comments: @comments } %>
        </div>
        <div class="pagenate">
          <%= paginate @comments %>
        </div>
      </div>
      <div class="col-md-4">
        <% if user_signed_in? %>
          <%= render partial: 'comments/form', locals: { project: @project, comment: @comment } %>
        <% else %>
          <div>
            <%= link_to new_user_registration_path, class: "btn btn-success" do %>
              <h2>ログイン</h2>
              <br>
              ログインすると、コメント・いいねが可能です！
          <% end %> 
          </div>
        <% end %>
      </div>
    </div>
  </div>