config/routes.rb
Rails.application.routes.draw do

  namespace :admins do
    get 'top' => 'homes#top', as:'top'  
  end
  devise_for :admins, controllers: {
  sessions:      'admins/sessions'
}


  get 'jobs/index'
  get 'jobs/edit'
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:index,:show,:create,:edit, :update, :destroy] do
    resources :nicetry, only: [:create,:destroy]
  end

  resources :jobs, only: [:index,:create, :edit, :update, :destroy]

  resources :projects do
    resource :favorites
    resources :comments, only: [:create, :destroy]
  end

  root 'homes#about'
  get '/homes/inquery' => 'homes#inquery'
  post '/homes/guest_sign_in', to: 'homes#new_guest'


end

app/views/layouts/_flash_messages.erb
<% if flash[:success] %>
  <div  class="alert alert-success"><%= flash[:success] %></div>
<% end %>
<% if flash[:danger] %>
  <div  class="alert alert-danger"><%= flash[:danger] %></div>
<% end %>
<% if flash[:notice] %>
  <div  class="alert alert-info"><%= flash[:notice] %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kaizen</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--awesomeの導入-->
  <script src="https://kit.fontawesome.com/9f81cad960.js" crossorigin="anonymous"></script>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <!--gem gonの導入-->
    <%= include_gon %>
  </head>
  <body>

  <!------------------------------------------------------
  ###                 ##
  ##
  ##  ##   ####     ###     ######    ####    #####
  ## ##       ##     ##     #  ##    ##  ##   ##  ##
  ####     #####     ##       ##     ######   ##  ##
  ## ##   ##  ##     ##      ##  #   ##       ##  ##
  ##  ##   #####    ####    ######    #####   ##  ##
  --------------------------------------------------------->
    <div class="container-fluid">
      <div class= "row">
        <div class= "col-md-12">
          <header class="navbar navbar-fixed-top bg-light">
            <div class="navbar__left">
              <%= link_to(image_tag('https://image-files-original-niduka.s3-ap-northeast-1.amazonaws.com/store/logo_1.png'), root_path, 'data-turbolinks': false ) %>
              
            </div>
            <div class="navbar__right">
              <% if user_signed_in? %>
                <%= link_to("マイページ",user_path(current_user.id)) %>
                <%= link_to("提案する", new_project_path) %>
                <%= link_to("提案一覧", projects_path) %>
                <%= link_to("会員一覧", users_path, 'data-turbolinks': false ) %>
                <%= link_to("職業一覧", jobs_path) %>
                <%= link_to(" ログアウト", destroy_user_session_path,'data-turbolinks': false) %>
              <% else %>
                <%= link_to("ログイン", new_user_session_path)%>
                <%= link_to("新規登録",new_user_registration_path,'data-turbolinks': false)%>


              <% end %>
            </div> 
            <div class="menu-icon" id="sp-menu">
              <h2 class="text-center">MENU</h2>
                <% if user_signed_in? %>
                <ul>
                  <li><%= link_to("提案する",new_project_path) %></li>
                  <li><%= link_to("提案一覧",projects_path) %></li>
                  <li><%= link_to("会員一覧",users_path, 'data-turbolinks': false ) %></li>
                  <li><%= link_to("職業一覧",jobs_path) %></li>
                  <li><%= link_to(" ログアウト", destroy_user_session_path,'data-turbolinks': false) %></li>
                </ul>
              <% else %>
                <ul>
                  <li><%= link_to("ログイン", new_user_session_path)%></li>
                  <li><%= link_to("会員登録", new_user_registration_path)%></li>
                </ul>
              <% end %>
            </div>
            <div id="hm-icon">
              <a class="menu-trigger">
                <span></span>
                <span></span>
                <span></span>
              </a>
            </div>
          </header>
        </div>
      </div>
    </div>
    <section class="section section-a">
    </section>
    <section class="section section-b">
    </section>
    <div class="container-fluid text-center">
      <%= render 'layouts/flash_messages' %>
      <%= yield %>
    </div>
    <div class="container-fluid">
      <div class="row">
        <footer class=" footer">
            <div class="col-md-4 footer__left">
                <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="fab fa-twitter-square" data-hashtags="KAIZENを使ってみよう！" data-show-count="false"></a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
                <a href="https://github.com/nizutaro/kaizen_portfolio" class="fab fa-github"></a>
          </div>
          <div class="col-md-4 center-list">
            <p class="copyright">&copy; 2020 yuta niduka</p>
          </div>
          <div class="col-md-4 right-list">
            <ul>
              <li><%=link_to("管理者ページ", new_admin_session_path) %></li>
            </ul>
          <div>
        </footer>
      </div>
    </div>
  </body>
</html>